version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "noriega"
    commit-message:
      prefix: "cargo"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday" 
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "noriega"
    commit-message:
      prefix: "ci"
      include: "scope" 