# Clippy configuration for professional CLI development
msrv = "1.70.0"

# Complexity thresholds
cognitive-complexity-threshold = 25
type-complexity-threshold = 200
too-many-arguments-threshold = 8
too-many-lines-threshold = 120

# Performance and safety
enum-variant-size-threshold = 200
trivial-copy-size-limit = 128

# Documentation requirements
missing-docs-in-crate-items = true

# Additional settings (compatible with all Clippy versions)
avoid-breaking-exported-api = false 