# rustfmt configuration for professional CLI development (stable features only)
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Import organization (stable features)
reorder_imports = true
reorder_modules = true

# Code style for CLI apps (stable features)
use_try_shorthand = true
use_field_init_shorthand = true

# Safety and readability (stable features)
remove_nested_parens = true
force_explicit_abi = true

# Professional formatting (stable features)
merge_derives = true 